kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: {{ include "team-video.fullname" . }}-web
  labels:
    app: {{ include "team-video.fullname" . }}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "team-video.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "team-video.fullname" . }}-web
      annotations:
        timestamp: "{{ now | unixEpoch }}"
    spec:
      containers:
       - name: web
         image: jitsi/web
         ports:
          - name: web
            containerPort: 80
         env:
          - name: JICOFO_AUTH_USER
            value: focus
          - name: XMPP_DOMAIN
            value: {{ .Values.app.name }}.{{ .Values.app.domain }}
          - name: XMPP_AUTH_DOMAIN
            value: auth.{{ .Values.app.name }}.{{ .Values.app.domain }}
          - name: XMPP_BOSH_URL_BASE
            value: http://{{ include "team-video.fullname" . }}-prosody:5280
          - name: XMPP_MUC_DOMAIN
            value: muc.{{ .Values.app.name }}.{{ .Values.app.domain }}
          - name: TZ
            value: Europe/Paris
          - name: PUBLIC_URL
            value: "https://{{ .Values.app.name }}.{{ .Values.app.domain }}"
          - name: SHOW_JITSI_WATERMARK
            value: "false"
          - name: SHOW_WATERMARK_FOR_GUESTS
            value: "false"