apiVersion: v1
kind: Secret
metadata:
  name: ddclient-secret
  labels:
    app: ddclient
stringData:
  ddclient.conf: |
    daemon=300
    syslog=yes
    ssl=yes
    protocol=dyndns2
    use=web
    web=http://checkip.twodns.de/
    web-skip='IP Address'
    server=update.twodns.de
    login=erika.mustermann@t-online.de
    password='My-S3cr3t-Passw0rd'
    teams.my-wan.de
