app:
  name: video
  domain: example.org
  pullpolicy: IfNotPresent

auth:
  enabled: false
  guests: true
  type: "internal"
  admin:
    user: admin
    password: "jitsiAdmin"

logLevel: "info"
hideWelcomePage: true

stun:
  server:

# optional changes below this line.
#  hint: use `openssl rand -base64 15`
#  to generate random secrets and endpoints
secrets:
  jvb:
    component: "i1IlhGQXt/eS61BpGckT"
    auth: "tCAmMmd+Az1ryU87/3i0"
  jicofo:
    component: "FsGVFqY4hoA2y84Czvfx"
    auth: "GvynwD0gRTG/aJWY/n71"
