apiVersion: v1
kind: Secret
metadata:
  name: ddclient-secret
  labels:
    app: ddclient
stringData:
  ddclient.conf: |
    daemon=300
    syslog=yes
    ssl=yes
    protocol=dyndns2
    use=web
    web={{ .Values.ddns.checkip }}
    web-skip='IP Address'
    server={{ .Values.ddns.update }}
    login={{ .Values.ddns.user }}
    password='{{ .Values.ddns.auth }}'
    {{ .Values.app.domain }}
